version: '2'
services:

  postgres:
    container_name: clair_postgres
    image: arminc/clair-db:latest
    ports:
      -  "5432:5432"

  clair:
    container_name: clair_clair
    image: arminc/clair-local-scan:v2.0.6
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
